apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/letfn/katt-kuma/zone?ref=0.0.7

patches:
  - path: patch-deployment-kuma-control-plane.yaml
    target:
      kind: Deployment
      name: kuma-control-plane

