apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/letfn/katt-cilium/base?ref=0.0.6

patches:
  - path: patch-configmap-cilium-config-cluster-mesh.yaml
    target:
      kind: ConfigMap
      name: cilium-config
